version: 2.1

orbs:
  go: circleci/go@1.8.0
  slack: circleci/slack@4.10.1

jobs:
  release:
    docker:
      - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Checkout monorepo"
          command: |
            git clone https://github.com/ethereum-optimism/optimism
      - run:
          name: "Capture Data"
          command: |
            make capture-chain-test-data
          working_directory: optimism/op-program
      - run:
          name: "Upload Data"
          command: ./upload-data.sh

workflows:
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
